### ISSUE TITLE
[ERROR] 最近的更新导致网站不能访问

### ISSUE THREAD

**Issue by MuelNova** [thdlrt/CsNotes#1]
疑似路由被破坏了？
![image](https://github.com/thdlrt/CsNotes/assets/68760718/cbee27f8-ae11-457a-bbf8-f31a8a7fbbbf)

**Comment by thdlrt** [comment]
更新了网站，加了导航栏，已经修好了。ヾ(*´∀ ˋ*)ﾉ
![image](https://github.com/thdlrt/CsNotes/assets/102659095/94cfdf57-bdd0-472b-8cfd-c631f1ca28c9)

**Comment by MuelNova** [comment]
(⁠◠⁠‿⁠・⁠)⁠—⁠☆感谢
